### ISSUE TITLE
Current Power not registering

### ISSUE THREAD

**Issue by Schroemges** [biemond/com.athom.zevercloud#3]
Hi Edwin,

FYI
It seems that the app is not working properly as of this morning ?!
I mean the Current power is not showing in the insights.
It does not show in the homey app screen 
And last but not least it does not show it in the new Energy tab ofc...

The E-Today is working fine.

Could you please look into this ?
I restarted the app in Homey and I also restarted Homey still the same issue.

With kind regards,
Dave Schroemges

**Comment by Schroemges** [comment]
![Screenshot_20191107-094310_Homey](https://user-images.githubusercontent.com/39372298/68373506-5cd32700-0143-11ea-8360-e8c6096a16f7.jpg)
![Screenshot_20191107-094340_Samsung Internet](https://user-images.githubusercontent.com/39372298/68373507-5d6bbd80-0143-11ea-8588-d86d39e0b786.jpg)
![Screenshot_20191107-094234_Homey](https://user-images.githubusercontent.com/39372298/68373508-5d6bbd80-0143-11ea-9394-b1222a3f5a23.jpg)

**Comment by biemond** [comment]
Hi,

Sorry for that , to add seversolar to energy I had to rename 1 of the measurements.  You need to remove the device and add it again.  Please check/ save  the api key 1st.

Hope this helps.

**Comment by Schroemges** [comment]
Hi Edwin,

Cool thank you very much for your help...
It works fine now. 

Maybe you need to explain this in your release note.
And let people know that they loose all there loggings ...
I just saw by removing my device it is all gone ofcourse, for me it is not that big of a problem but for some it might be ;-)

With kind regards,

Dave

**Comment by biemond** [comment]
nice, I added it to the change log but now I see it is not shown on the mainpage. Will change that. Plus maybe add this E-total to the overview

**Comment by Schroemges** [comment]
Thanks Edwin, much appreciated.
