### ISSUE TITLE
Homey Zevercloud app leest de api niet meer ?

### ISSUE THREAD

**Issue by Schroemges** [biemond/com.athom.zevercloud#4]
Hoi Edwin,

Heb jij enig idee waarom jouw Zevercloud app mijn api niet meer leest sinds gisteren ?

mvg Dave

**Comment by biemond** [comment]
He Dave,

inderdaad , 1 van hun api doet het niet meer 
 https://www.zevercloud.com/api/v1/getPlantOverview

andere nog wel , Ik heb ze gemailed maar ik weet niet of ze daarop reageren.

**Comment by Schroemges** [comment]
Hoi Edwin,

Dank voor je snelle feedback we zullen zien.
Ik houd je op de hoogte.

Mvg Dave

**Comment by biemond** [comment]
ze hebben gereageerd en ze hebben mij de nieuwe api doc toegestuurd.  Ik zal dat vanavond eens uitproberen en als het goed is vanavond een test release publiceren.

**Comment by biemond** [comment]
blijkbaar hebben ze hun oude api disabled maar ik weet wat ik nu moet doen, ( a signing request met een key en secret)
daarna kan ik deze token gebruiken voor de echte api met de device api als key .

helaas kan ik niet meer inloggen op de site en ik heb ze weer gemailed.  als dit werkt moet wel iedereen een key en secret bij hun sales of support aanvragen.

gr

**Comment by Schroemges** [comment]
Oh dat is goed nieuws...
Moet ik iets doen of kan ik iets doen ?
Wel vreemd dat ze dat zomaar afschakelen.

**Comment by biemond** [comment]
ja , ik denk dat ze ons niet door hadden dat wij nog de oude gebruiken.  ik lees dat anderen dit al 2 jaar moeten doen.
ik ga het nu handmatig testen zodat ik het daarna het kan toevoegen aan de app.

gr

**Comment by biemond** [comment]
Het werkt voor mij met deze endpoint  http://api.general.zevercloud.cn/getPlantOverview.  ik heb nu naast de api key nu ook een secret en appkey nodig.  Nu nog omzetten naar nodejs
```
[INFO] Running com.aliyun.api.gateway.demo.Demo
{"body":"{\"sid\":53121,\"ludt\":\"2020-12-01 17:03:23\",\"status\":\"0\",\"E-Today\":{\"unit\":\"KWh\",\"value\":0.5},\"E-Month\":{\"unit\":\"KWh\",\"value\":0.5},\"E-Total\":{\"unit\":\"MWh\",\"value\":3.27},\"TotalYield\":{\"unit\":\"€\",\"value\":2289.69},\"CO2Avoided\":{\"unit\":\"T\",\"value\":2.62},\"Power\":{\"unit\":\"W\",\"value\":0}}","contentType":"text/plain;charset=UTF-8",...,"statusCode":200}
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.17 s - in com.aliyun.api.gateway.demo.Demo
```

**Comment by Schroemges** [comment]
Ik zal mijn DeviceID ,Secret + Api bij mijn Zonnepaneel aanbieder (Zonneplan) opvragen.

**Comment by biemond** [comment]
inderdaad , ik heb ze opgevraagd bij service.eu@zeversolar.net het zijn verborgen velden bij account settings.

**Comment by Schroemges** [comment]
IK heb de Doc gekregen en ze hebben mij de APPkey en APPSecret gekregen en is toegevoegd aan mijn account.
Ik wacht rustig af zodat ik deze kan invoeren in joue app.

**Comment by biemond** [comment]
perfect. de app komt er aan.

**Comment by biemond** [comment]
node script , it works , only need to add the new 2 params to the app. but this will be breaking I guess.

```
const crypto = require('crypto');
const https = require('http')

var appSecret = 'xxxxxxx';
const appKey = 'xxxxxx';
const apiKey = 'xxxxx';

const op = 'GET';
const accept = 'application/json';
const time = Date.now();

const payload = op.concat('\n', accept,'\n\n\n',
                      '\nX-Ca-Key:', appKey,
                      '\nX-Ca-Timestamp:', time,
                      '\n/getPlantOverview?key=', apiKey );

console.log(payload);

const signedHeaders = "X-Ca-Signature-Headers: X-Ca-Key,X-Ca-Timestamp"

/*
GET
application/json



X-Ca-Key:xxx
X-Ca-Timestamp:1607109536050
/getPlantOverview?key=xxxx
*/

let signature = crypto.createHmac('sha256', appSecret).update(payload).digest("base64")

console.log(signature);

// 2020/12/04 20:20:12:126 CET [DEBUG] wire - >> "X-Ca-Timestamp: 1607109611458[\r][\n]"
// 2020/12/04 20:20:12:126 CET [DEBUG] wire - >> "Accept: application/json[\r][\n]"
// 2020/12/04 20:20:12:126 CET [DEBUG] wire - >> "X-Ca-Key: xxxx[\r][\n]"
// 2020/12/04 20:20:12:126 CET [DEBUG] wire - >> "X-Ca-Signature: v7UwJ+Lyu7EwdiWggCma6psZOyY48QoHBwz0FmRTuvs=[\r][\n]"
// 2020/12/04 20:20:12:127 CET [DEBUG] wire - >> "X-Ca-Signature-Headers: X-Ca-Key,X-Ca-Timestamp[\r][\n]"


const options = {
    protocol: 'http:',
    method: 'GET',
    headers: {
        'X-Ca-Timestamp': time,
        'Accept': accept,
        'X-Ca-Key': appKey,
        'X-Ca-Signature': signature,
        'X-Ca-Signature-Headers': 'X-Ca-Key,X-Ca-Timestamp'
    }
}
options.hostname = 'api.general.zevercloud.cn';
options.path = '/getPlantOverview?key='+ apiKey;

const reqX = https.request(options, resX => {
    console.log('-------------------');
    console.log(`statusCode: ${resX.statusCode}`);
    console.log(resX.headers);

    let body = "";
    resX.on("data", data => {
      body += data;
    });
    resX.on("end", () => {
        console.log(JSON.parse(body));
    });
})  

reqX.on('error', error => {
    console.error(error)
})
reqX.end()
```

**Comment by biemond** [comment]
he kun je deze testen https://homey.app/nl-nl/app/com.athom.zevercloud/ZeverCloud-Solar-Power/test/
je moet wel de secret and app key toevoegen aan de device. (opvragen bij service.eu@zeversolar.net )

**Comment by Schroemges** [comment]
![Screenshot_20201205-201002_Homey](https://user-images.githubusercontent.com/39372298/101261266-3f053680-3736-11eb-909f-ba4d81212fb7.jpg)
Schijnt werken morgen weet ik meer ik houd je op de hoogte Edwin thx m8

**Comment by biemond** [comment]
mooi, heb je weiland of een schuur met panelen. vandaag had je 8.5kwh , ik had 0.5 met 8 panelen.

**Comment by Schroemges** [comment]
Lol, ik heb 12 x 295 Wp maar hier in Noord Limburg scheen best veel de zon dus dat verklaard ;-)

**Comment by Schroemges** [comment]
![Screenshot_20201206-101015_Homey](https://user-images.githubusercontent.com/39372298/101276141-516d8780-37ab-11eb-9c89-c4272de30475.jpg)
Oh yes, Homey is registering again. :-)

**Comment by biemond** [comment]
![Screenshot_20201206-120041](https://user-images.githubusercontent.com/1085004/101278327-e0ce6700-37ba-11eb-896a-b1ab5386711c.jpg)
yep nice

**Comment by Schroemges** [comment]
Hoi Edwin,

Ik zag jij hebt Zevercloud geupdate de test versie die ik heb geïnstalleerd in Homey hoef ik niet opnieuw te installeren he mijne die nu op mijn Homey staat is nu de LIVE versie toch ?
Verder wil ik jouw erg bedanken voor je aanpassingen en support top werk.
mvg Dave

**Comment by biemond** [comment]
he inderdaad,  ik had zo'n 80 crash logs gekregen.  de crash heb ik gefixed en ook deze wordt automatisch geïnstalleerd.

dank je wel. geniet ervan.

**Comment by Schroemges** [comment]
Hoi Edwin zou je eens willen kijk als je tijd hebt iets gaat nog niet geheel lekker met de weergaven (punt of komma misschien) Watt wel maar niet de kW...
![Screenshot_20201225-111802_Homey](https://user-images.githubusercontent.com/39372298/103133797-c1857400-46ac-11eb-8377-6394394dcab8.jpg)

**Comment by biemond** [comment]
Ik zie het. ik zal eens kijken.  ik vermoed dat severcloud mij kw of watt terug geeft afhankelijk als het meer dan  1000 watt is.

**Comment by biemond** [comment]
kan je ook een pic maken wanneer je op zonnepanelen klikt. of insights.  vooral benieuwd naar de overgang naar 1kw en terug.

**Comment by biemond** [comment]
misschien is het een weergave bug https://github.com/biemond/com.athom.zevercloud/blob/master/drivers/plant/device.js#L212.  ben benieuwd naar jouw insights 
misschien de unit is nu niet meer "kW"


```
{
  sid: 53121,
  ludt: '2020-12-25 13:25:23',
  status: '1',
  'E-Today': { unit: 'KWh', value: 0.4 },
  'E-Month': { unit: 'KWh', value: 11.04 },
  'E-Total': { unit: 'MWh', value: 3.28 },
  TotalYield: { unit: '€', value: 2297.07 },
  CO2Avoided: { unit: 'T', value: 2.63 },
  Power: { unit: 'W', value: 133 }
}
```

**Comment by biemond** [comment]
Ik zie ook KW in een voorbeeld. nu maar omgedraaid check nu voor watt en anders is het kW, dan weet ik het zeker

https://homey.app/nl-nl/app/com.athom.zevercloud/ZeverCloud-Solar-Power/test/

**Comment by Schroemges** [comment]
Ships ik d8 voor jij mij emailde probeer de app eens te verwijderen uit homey en opnieuw te installeren.
Kreeg eerst de melding dat het niet lukte, toen Homey gereboot en alles opnieuw ingevuld van zevercloud krijg nu dit. Had ik beter niet kunnen doen.
![Screenshot_20201225-141203_Homey](https://user-images.githubusercontent.com/39372298/103135828-7aeb4600-46bb-11eb-9b26-0f41f93474d3.jpg)

**Comment by Schroemges** [comment]
Ik zal even jouw beta versie testen.

**Comment by Schroemges** [comment]
Krijg dezelfde melding van jouw beta versie als op de foto hierboven vreemd.

**Comment by biemond** [comment]
via mijn https://my.homey.app/ kan je nu gemakkelijk je keys weer invullen.

**Comment by Schroemges** [comment]
Ja mooi he eindelijk weer een webapp eerst willen ze van webapp af en naar mobile only en weer terug hahahaha
Ik test straks of morgen wel even op de laptop zit lekker tv te kijken met de vriendin. Komt goed Edwin fijn kerst m8

**Comment by Schroemges** [comment]
![Screenshot_20201228-103433_Homey](https://user-images.githubusercontent.com/39372298/103204768-57610f00-48f8-11eb-879f-fdd2b3c56a44.jpg)
Werkt ;-)

**Comment by biemond** [comment]
nice, wat een zon in limburg. zo verboden moeten worden. gelukkig hier ook een beetje
